# Generated by Django 6.0.7 on 2026-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text="True for accounts created via the 'Continue as Guest' flow: no email/password, temporary access so a learner can try the platform before deciding to create a full account."),
        ),
    ]
