# Generated by Django 6.0.7 on 2026-07-25 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('current_level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency / Mastery')], default='A1', max_length=2)),
                ('passed_levels', models.JSONField(default=list, help_text='CEFR levels that scored >= threshold, in order.')),
                ('result_level', models.CharField(blank=True, help_text='Final assessed level, e.g. "B1", or "Pre-A1" if A1 was not passed.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Original id from the source JSON, e.g. "B2-014".', max_length=20)),
                ('skill', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing')], max_length=20)),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency / Mastery')], max_length=2)),
                ('question_type', models.CharField(help_text='Original "type" field from the source JSON (e.g. "meaning", "grammar").', max_length=30)),
                ('prompt', models.TextField(help_text='The question text shown to the test-taker.')),
                ('options', models.JSONField(help_text='Always exactly 4 answer choices.')),
                ('correct_answer', models.CharField(help_text='Exact copy of the correct string from `options`.', max_length=500)),
                ('tag', models.CharField(blank=True, help_text='word_tested (vocabulary) or grammar_point (grammar).', max_length=255)),
            ],
            options={
                'ordering': ['skill', 'level', 'external_id'],
                'indexes': [models.Index(fields=['skill', 'level'], name='assessment__skill_1bf9be_idx')],
                'constraints': [models.UniqueConstraint(fields=('skill', 'external_id'), name='unique_external_id_per_skill')],
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency / Mastery')], max_length=2)),
                ('order', models.PositiveSmallIntegerField()),
                ('selected_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='assessment.placementsession')),
            ],
            options={
                'ordering': ['session', 'level', 'order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
